/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Portal(props) {
  const { nodes, materials } = useGLTF('./model/portal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.poleLightA.geometry} material={nodes.poleLightA.material} position={[0.71, 1.07, 0.23]} />
      <mesh geometry={nodes.portalLight.geometry} material={nodes.portalLight.material} position={[0, 0.85, -1.77]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.poleLightB.geometry} material={nodes.poleLightB.material} position={[-0.64, 1.07, 0.23]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.baked.geometry} material={nodes.baked.material} />
    </group>
  )
}

useGLTF.preload('/portal.glb')
